[package]
name = "tsunami"
version = "0.11.0-beta.3"
edition = "2018"

description = "Toolkit for running short-lived jobs on cloud VMs"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>", "Akshay Narayan <akshayn@mit.edu>"]

documentation = "https://docs.rs/tsunami"
homepage = "https://github.com/jonhoo/tsunami"
repository = "https://github.com/jonhoo/tsunami.git"

keywords = ["ec2", "aws", "azure", "vm", "spot-instances", "distributed", "benchmark"]
categories = []

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/tsunami" }
maintenance = { status = "passively-maintained" }

[features]
debug = ["slog/max_level_trace", "slog/release_max_level_debug"]

[dependencies]
educe = "0.4"
failure = "0.1.1"
futures-util = "0.3.4"
itertools = "0.8"
rand = "0.7"
rayon = "1.0.0"
rusoto_core = "0.43.0"
rusoto_ec2 = "0.43.0"
serde_json = "1"
serde = { version = "1", features = ["derive"]}
sessh = "0.2.0"
slog = "2.1.1"
#slog = { version = "2.1.1", features = ["max_level_trace"] }
slog-term = "2.4.0"
ssh2 = "0.8"
structopt = "0.2"
tempfile = "3.0.0"
tokio = { version = "0.2.0", features = ["rt-core"] }

[dev-dependencies]
rusoto_sts = "0.43.0"

[profile.release]
debug = true
